### PR TITLE
Fixes for Sumo

### PR DESCRIPTION
**Pull request by htot**
This changes dependency from 'iwconfig' to 'iw', fixes the path for hostapd.conf
and fixes shelljs 'shell.exec' returning 'stdou't instead of 'output' in nodejs (8.9.4 in Sumo)

It does not yet show the list of available AP's

### CODE REVIEW

**Comment by alext-mkrs** [comment]
So the hostapd.conf part is already in #1, so I don't think it makes sense to have it here - I'll just merge that. The other two I'd suggest to split to two different commits as those are logically independent changes.

**Review by alext-mkrs — CHANGES_REQUESTED** [review]
So the hostapd.conf part is already in #1, so I don't think it makes sense to have it here - I'll just merge that. The other two I'd suggest to split to two different commits as those are logically independent changes.

**Comment by htot** [comment]
I just wanted to share my changes (in a hurry). Thanks for the comments, I'll fix and resend.

**Review by alext-mkrs — APPROVED** [review]

**Comment by alext-mkrs** [comment]
Thanks, LGTM.

**Comment by htot** [comment]
This fixes the issues above. 

Still `configure_edison --wifi` doesn't work. The reason is `wpa_cli scan` returns:
`Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory`

This interface also may need replacement (quick googled). 

`connmanctl scan wifi && connmanctl services` works, but does not show the bssid / frequency /signal level / encryption flags / ssid `wpi_cli` does. We can retrieve them with `connmanctl service --properties <service> `.
Or we could use `iw`, I found this one liner:
`iw dev wlan0 scan | egrep "signal|SSID" | sed -e "s/\tsignal: //" -e "s/\tSSID: //" | awk '{ORS = (NR % 2 == 0)? "\n" : " "; print}' | sort` which outputs:
```
-58.00 dBm TP-LINK_941F4A
-68.00 dBm Oranje Plantage 35 2.4G
-74.00 dBm 
-79.00 dBm Oranje Plantage 35 5G
-80.00 dBm ANNE
-85.00 dBm H369A6D5E05
-88.00 dBm Ziggo
```
Not too bad. What do you think?

**Comment by alext-mkrs** [comment]
Yes, I thin the `iw` one looks more promising - so that we use the same tool as much as we can (and we already started using it with your newest patch).

**Comment by htot** [comment]
Same here. I like `connmanctl`, for interactively connecting. `iw` looks like a bit more suitable for calling from a script. Only problem, I don't know python. May be save that for a separate PR?

**Comment by alext-mkrs** [comment]
Yeah, definitely, in this sense I believe this should be a separate one as I think that might be a bigger endeavor. I do Python rather frequently, so I can take care of that BTW.

**Comment by htot** [comment]
I was hoping you would say that :-). Merged this.

**Pull request merged**
