### PR TITLE
configure_edison fixes

### PR DESCRIPTION
**Pull request by mwallnoefer**
Now the console-based tool works again

### CODE REVIEW

**Comment by htot** [comment]
That's a lot of changes! Let me try that and get back here.

**Comment by mwallnoefer** [comment]
Okay, now I managed to enable also half of the web UI part :smile:

**Review by htot — DISMISSED** [review]

**Comment by htot** [comment]
Too much work to review line by line :-)

Instead I started testing.
What I have:
1) usb ethernet adapter. When the usb is in hostmode:
```
connmanctl> services 
*AR Wired                ethernet_00800f951d4d_cable
```
2) ethernet over usb (gadget)
```
connmanctl> services 
*AR Wired                gadget_aabbccddeef1_usb
```

As shown they are in fallback mode because there is also 
3) wifi:
```
connmanctl> services 
*AO OP35 Extra 5G        wifi_784b87ad4d70_4f503335204578747261203547_managed_psk
```
Further I can
4): setup my phone as bluetooth tether
```
connmanctl> services 
* R ZTE Ferry            bluetooth_984FEE03CAE9_6073BC238F3E
```
As shown in fallback mode, not autoconnected.

So, we can have wired (either dongle or gadget) at the same time with bluetooth tether and wifi AP.
And the devices can be powered on/off.

Detection of gadget is currently not working
afbeelding

With bluetooth partly (ethernet address is detected)
afbeelding

But the enable (powered) button is broken (can not click and mispositioned).

My idea was detect the wifi networks, wires device etc. But don't change anything until user clicks the last tab as that might break connections. But in the right order going from wifi (primary) -> wired (fall back) + wifi (primary) -> wired (primary) + wifi AP will work.

These detections have worked in the past (thud), I don't know if they broke because of warrior/zeus. But actually storing user changes until the Activate tab was never finished.

But I am really happy with what you are doing to the code. You are clearly much better in python then me. So I will pull all your patches into rewrite-wip and once it starts working pull that into master.

Thanks!

**Comment by mwallnoefer** [comment]
Regarding the Web interface: I have to add that **I did not fix** _cable Ethernet_ (including _gadget_) and _Bluetooth Ethernet_ yet. What regards to _cable Ethernet_ and _gadget_ I would have the cables/adapters, for _Bluetooth Ethernet_ I don't know :unamused:. So if you would contribute here, you're welcome!
Also the WiFi and AP settings get currently applied instantly, and not after clicking the button in the last tab.

My work concentrated more on the handy `configure_edison` cmdline tool, which I enjoyed since the beginning. And concurrent platforms like Raspberry PI do not provide it at all :smile: .

**Comment by htot** [comment]
If you have a android phone, you only need to enable bluetooth tethering, that's all.

I liked to use the `configure_edison` cmdline tool, but connman has evolved a lot since, so once you have terminal access I find connman does almost all you need.

My ifirst dea was: by pushing the push button you can pair your phone with bt or enable the AP and use your phone browser to configure connection to the local wifi network. And now it seems to be evolving into a web gui to connman :-)

**Pull request merged**
