### PR TITLE
configure_edison: correct hostapd.conf path

### PR DESCRIPTION
**Pull request by alext-mkrs**
On current images, the location is different than it used to be. This fixes a part of https://github.com/edison-fw/meta-intel-edison/issues/24.

### CODE REVIEW

**Comment by htot** [comment]
In addition in dmesg I find:
```
ap-mode-toggle[2438]: Usage: /usr/bin/ap-mode-toggle start|stop|toggle
ap-mode-toggle[2438]:   start  - Start AP mode
ap-mode-toggle[2438]:   stop   - AP mode is stopped and we return to station mode
ap-mode-toggle[2438]:   toggle - Start or stop AP mode depending on previous mode.
ap-mode-toggle[2438]: This script is only usable in Edison where the Broadcom
ap-mode-toggle[2438]: wifi driver firmware needs to be told which mode to operate.
```
I don't know what it does, but that might need work too?

**Comment by alext-mkrs** [comment]
Yes, this looks like a separate problem - which may have to do with the wifi/bt module names changing between versions, as `ap-mode-toggle` does e.g. `modprobe bcm4334x op_mode=2`

**Comment by alext-mkrs** [comment]
Ok, so as you've included the same fix into your PR, I assume this is an approval :) and proceed with merging. Further fixes we'll discuss separately (and looks like there will be several of those as things have changed around).

**Comment by htot** [comment]
I sorry, I missed your change. You are right, I of course agree to apply.

**Pull request merged**
